#!/bin/sh
nft add rule ip filter INPUT iifname $SERVER_PUB_NIC udp dport $SERVER_PORT counter accept comment "WireGuardGamingInstaller"
nft add rule ip filter FORWARD iifname $SERVER_PUB_NIC oifname $SERVER_WG_NIC counter accept comment "WireGuardGamingInstaller"
nft add rule ip filter FORWARD iifname $SERVER_WG_NIC counter accept comment "WireGuardGamingInstaller"
nft add rule ip nat POSTROUTING oifname $SERVER_PUB_NIC counter masquerade comment "WireGuardGamingInstaller"
nft add rule ip6 filter INPUT iifname $SERVER_PUB_NIC udp dport $SERVER_PORT counter accept comment "WireGuardGamingInstaller"
nft add rule ip6 filter FORWARD iifname $SERVER_PUB_NIC oifname $SERVER_WG_NIC counter accept comment "WireGuardGamingInstaller"
nft add rule ip6 filter FORWARD iifname $SERVER_WG_NIC counter accept comment "WireGuardGamingInstaller"
nft add rule ip6 nat POSTROUTING oifname $SERVER_PUB_NIC counter masquerade comment "WireGuardGamingInstaller"

# DNAT from 53,80,88,500, 1024 to 65000"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC udp dport 53 counter dnat to $CLIENT_WG_IPV4:53 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 53 counter dnat to $CLIENT_WG_IPV4:53 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC udp dport 80 counter dnat to $CLIENT_WG_IPV4:80 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 80 counter dnat to $CLIENT_WG_IPV4:80 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC udp dport 88 counter dnat to $CLIENT_WG_IPV4:88 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 88 counter dnat to $CLIENT_WG_IPV4:88 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC udp dport 500 counter dnat to $CLIENT_WG_IPV4:500 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 500 counter dnat to $CLIENT_WG_IPV4:500 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC udp dport 1024-65000 counter dnat to $CLIENT_WG_IPV4:1024-65000 comment "WireGuardGamingInstaller"
nft add rule ip nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 1024-65000 counter dnat to $CLIENT_WG_IPV4:1024-65000 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC udp dport 53 counter dnat to [$CLIENT_WG_IPV6]:53 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 53 counter dnat to [$CLIENT_WG_IPV6]:53 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC udp dport 80 counter dnat to [$CLIENT_WG_IPV6]:80 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 80 counter dnat to [$CLIENT_WG_IPV6]:80 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC udp dport 88 counter dnat to [$CLIENT_WG_IPV6]:88 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 88 counter dnat to [$CLIENT_WG_IPV6]:88 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC udp dport 500 counter dnat to [$CLIENT_WG_IPV6]:500 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 500 counter dnat to [$CLIENT_WG_IPV6]:500 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC udp dport 1024-65000 counter dnat to [$CLIENT_WG_IPV6]:1024-65000 comment "WireGuardGamingInstaller"
nft add rule ip6 nat PREROUTING iifname $SERVER_PUB_NIC tcp dport 1024-65000 counter dnat to [$CLIENT_WG_IPV6]:1024-65000 comment "WireGuardGamingInstaller"
